name: Compile dinput8.dll

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
            submodules: 'true'
      - uses: ilammy/msvc-dev-cmd@v1
        with: 
          arch: amd64_x86
      - name: Build something requiring CL.EXE
        run: |
          .\build.bat
      - uses: actions/upload-artifact@v7
        with:
          name: nfs-run-ffb-fix
          path: |
            dinput8.dll
            dinput8_proxy.ini